# Week one overview - Getting started and R nut and bolts

## 1. Introduction
## 2. Overview and history of R
## 3. Geting help
## 4. R Console input and evaluation


In [6]:
# entering input
x <- 1
print(x)
msg <- "Hello"
msg ## explicit printing doesn't work in scripting
# priting
x <- 1:20
print(x)

ERROR: Error in parse(text = x, srcfile = src): <text>:2:1: unexpected '<'
1: # entering input
2: <
   ^


## 5. Data types: R objects and attributes

### Objects (atomic classes)
* character
* numeric (real numbers) 
 * `Inf` means inifinity
 * `NaN` means 'not a number' (undefined value)
* integers (L suffix)
* complex
* logical
> The most basic object is a vector (list of objects from the same type)

### Attributes
* names, dimnames
* dimensions
* class
* length
* others user-defined attributes/metadata
> Attributes can be accessed using `attributes()` function

## 6. Data types: Vectors and lists


In [14]:
# Creating vectors
print("--- Creating vectors ---")
x <- c(0.5, 0.6)  # numeric
y <- c(TRUE, F)  # logical
z <- c("a", "b", "c")  # character
a <- 9:29  # integer
b <- c(1+0i, 2+4i)  # complex

c <- vector("numeric", length=10)
print(c)

# Mixing objects
print("--- Mixing objects ---")
d <- c(1.7, "a")  # character
e <- c(T, 2)  # numeric
f <- c("a", T)  # character

# Explicit coersion
print("--- Explicit coersion ---")
g <- 0:6
class(g)
as.numeric(g)
as.logical(g)
as.character(g)

h <- c("a", "b", "c")
as.numeric(h)
as.logical(h)
as.complex(h)

# Lists: Type of object wich can contain elements of different classes
print("--- Lists ---")
i <- list(1, "a", T, 1+4i)
print(i)

[1] "--- Creating vectors ---"
 [1] 0 0 0 0 0 0 0 0 0 0
[1] "--- Mixing objects ---"
[1] "--- Explicit coersion ---"


[1] "integer"

[1] 0 1 2 3 4 5 6

[1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

[1] "0" "1" "2" "3" "4" "5" "6"

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”

[1] NA NA NA

[1] NA NA NA

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”

[1] NA NA NA

[1] "--- Lists ---"
[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] TRUE

[[4]]
[1] 1+4i



## 7. Data types: Matrices

In [23]:
# Matrices: vectors with a dimension attribute (nrow and ncol)
m <- matrix(nrow=2, ncol=3)
print(m)
print(dim(m))
print(attributes(m))

# cont'd
m <- matrix(1:6, nrow=2, ncol=3)
print(m)

m <- 1:10
dim(m) <- c(2, 5)
print(m)

# cbind-ing / rbind-ing
print("--- cbind and rbind ---")
x <- 1:3
y <- 10:12
print(cbind(x, y))
print(rbind(x, y))

     [,1] [,2] [,3]
[1,]   NA   NA   NA
[2,]   NA   NA   NA
[1] 2 3
$dim
[1] 2 3

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10
[1] "--- cbind and rbind ---"
     x  y
[1,] 1 10
[2,] 2 11
[3,] 3 12
  [,1] [,2] [,3]
x    1    2    3
y   10   11   12


## 8. Factors
* Categorical data
* Unordered or ordered
* Integer vector where each integer has a label
* lm() and glm()


In [30]:
x <- factor(c("yes", "yes", "no", "yes", "no"))
print(x)
print(table(x))
print(unclass(x))

# order of levels
print("-- ordered --")
x <- factor(c("yes", "yes", "no", "yes", "no"),
           levels=c("yes", "no"))
print(x)

[1] yes yes no  yes no 
Levels: no yes
x
 no yes 
  2   3 
[1] 2 2 1 2 1
attr(,"levels")
[1] "no"  "yes"
[1] "-- ordered --"
[1] yes yes no  yes no 
Levels: yes no


## 9. Data types: Missing values
* Undefined mathematical operations (`NA` or `NaN`)
* test with `is.na()` and `is.nan()`
* `NA` values have class (can be integer, character, ..)
* `NaN` are `NA` but the converse are not true


In [33]:
x <- c(1, 2, NA, 10, 3)
print(is.na(x))
print(is.nan(x))
y <- c(1, 2, NaN, NA, 4)
print(is.na(y))
print(is.nan(y))

[1] FALSE FALSE  TRUE FALSE FALSE
[1] FALSE FALSE FALSE FALSE FALSE
[1] FALSE FALSE  TRUE  TRUE FALSE
[1] FALSE FALSE  TRUE FALSE FALSE


## 10. Data types: Data frames
* Special type of list with each element has the same length
* Columns x rows
* Can store differente classes for each column
* Nice attribute `row.names`
* Normally created using `read.table()` or `read.csv()`
* Can be converted to matrix using `data.matrix()`

In [36]:
df <- data.frame(foo=1:4, bar=c(T, T, F, F))
print(df)
print(nrow(df))
print(ncol(df))

  foo   bar
1   1  TRUE
2   2  TRUE
3   3 FALSE
4   4 FALSE
[1] 4
[1] 2


## 11. Data types: Names attribute

In [39]:
x <- 1:3
print(names(x))
names(x) <- c("foo", "bar", "norf")
print(names(x))

# for lists
lst <- list(a=1, b=2, c=3)
print(lst)

# for matrices
m <- matrix(1:4, nrow=2, ncol=2)
dimnames(m) <- list(c("a", "b"), c("c", "d"))
print(m)

NULL
[1] "foo"  "bar"  "norf"
$a
[1] 1

$b
[1] 2

$c
[1] 3

  c d
a 1 3
b 2 4


## 12. Data types: Summary
* atomic classes: numeric, logical, character, integer, complex
* vectors, lists
* factors
* missing values
* data frames
* names


## 13. Reading tabular data